const collection = [
  { title: "Supercar", text: "Supercar Cinematic Shoots", img: "./public/b.jpg" },
  { title: "Commercial", text: "Automotive Commercial Production", img: "./public/b.jpg" },
  { title: "Reels", text: "Social Media Car Reels", img: "./public/b.jpg" },
  { title: "Brand Launch", text: "Brand Launch Videos", img: "./public/b.jpg" },
  { title: "Drone Chase", text: "Drone Car Chase Footage", img: "./public/b.jpg" },
  { title: "Behind the Scenes", text: "Behind-the-Scenes Car Builds", img: "./public/b.jpg" },
  { title: "Details", text: "Car Detail Highlight Videos", img: "./public/b.jpg" },
  { title: "Engine Audio", text: "Engine Sound Design & Mixing", img: "./public/b.jpg" },
  { title: "Beauty Shots", text: "Rolling & Static Beauty Shots", img: "./public/b.jpg" },
  { title: "Dealership Promo", text: "Dealership Promotional Videos", img: "./public/b.jpg" },
  { title: "Test Drive", text: "Virtual Test Drive Videos", img: "./public/b.jpg" },
  { title: "Owner Story", text: "Owner Story Documentaries", img: "./public/b.jpg" },
  { title: "360 Tours", text: "360° Interior/Exterior Tours", img: "./public/b.jpg" },
  { title: "Mod Projects", text: "Time-Lapse Car Mod Projects", img: "./public/b.jpg" },
  { title: "Lifestyle", text: "Luxury Car Lifestyle Videos", img: "./public/b.jpg" },
  { title: "Track Day", text: "Track Day Video Coverage", img: "./public/b.jpg" },
  { title: "Event Recap", text: "Event Recap Films", img: "./public/b.jpg" },
  { title: "Slow-Mo", text: "Slow-Motion Engine/Exhaust Shots", img: "./public/b.jpg" },
  { title: "Teasers", text: "Teaser Trailers for Social", img: "./public/b.jpg" },
  { title: "Web Loops", text: "Website Background Video Loops", img: "./public/b.jpg" },
  { title: "TikTok", text: "Social Media Vertical Videos", img: "./public/b.jpg" },
  { title: "Documontaries", text: "Car Documontary Videos", img: "./public/b.jpg" },
  { title: "Music-Videos", text: "Supercars Music-Video Editing", img: "./public/b.jpg" },
  { title: "Podcast!", text: "Supercars Related Podcasts", img: "./public/b.jpg" },
  { title: "Supercar", text: "Supercar Cinematic Shoots", img: "./public/b.jpg" },
];

export default collection;